In [1]:
def my_function():
    "This prints a string"
    print("Hello from a function")

In [2]:
my_function()

Hello from a function


In [9]:
def printme(nama):
    "This prints a nama string into this function"
    print(nama)

In [4]:
printme("Kukuh") # argument

Kukuh


In [5]:
printme("nama saya adalah ...")

nama saya adalah ...


In [16]:
def printme(nama, alamat):# parameter #nama holds value Kukuh / nama saya adalah ...
    "This prints a nama string into this function"
    print(nama)
    print(alamat)

In [17]:
printme("Kukuh", "depok")

Kukuh
depok


In [18]:
printme()

TypeError: printme() missing 2 required positional arguments: 'nama' and 'alamat'

In [22]:
printme("Kukuh", "tj gading")

Kukuh
tj gading


In [23]:
printme(alamat= "tj gading", nama="Kukuh")

Kukuh
tj gading


In [24]:
def printme(nama = "Kukuh", alamat = "Tj gading"):
    "This prints a nama string into this function"
    print(nama)
    print(alamat)
    return

In [25]:
printme()

Kukuh
Tj gading


In [26]:
printme("Hacktive8")

Hacktive8
Tj gading


In [28]:
printme(alamat="Depok")

Kukuh
Depok


In [29]:
printme("Hacktiv8", "Depok")

Hacktiv8
Depok


In [36]:
def printinfo(arg1, *vartuple):
    "This prints a variable passed arguments"
    print("outputs is: ")
    print(arg1)
    for var in vartuple: 
        print(var)
    return

In [37]:
printinfo(30)

outputs is: 
30


In [38]:
printinfo(1, 2, 3, 4, 5, 6, 7, 8, 9)

outputs is: 
1
2
3
4
5
6
7
8
9


In [39]:
def printinfo(arg1, *arg2):
    "This prints a variable passed arguments"
    print("outputs is: ")
    print(arg1)
    for var in arg2: 
        print(var)
    return

In [40]:
printinfo(1, 2, 3, 4, 5)

outputs is: 
1
2
3
4
5


In [42]:
sum = lambda arg1, arg2: arg1 + arg2;

In [43]:
sum(10, 20)

30

In [44]:
print("Value of total:", sum(20, 20))

Value of total: 40


In [47]:
def sum(arg1, arg2):
    total = arg1 + arg2
    total1 = total + 50
    return total

In [48]:
sum(10, 20)

30

In [49]:
def sum(arg1, arg2):
    total = arg1 + arg2
    total1 = total + 50
    return total1

In [50]:
sum(10, 20)

80

In [52]:
def sum(arg1, arg2):
    total = arg1 + arg2
    total1 = total + 50
    return total, total1

In [53]:
sum(10, 20)

(30, 80)

In [56]:
kucing = 20 

def jumlahhewan():
    kelinci = 30 
    hewan = kucing + kelinci
    return hewan

In [57]:
jumlahhewan()

50

In [61]:
kucing = 20 

def jumlahhewan():
    kelinci = 30 
    hewan = kucing + kelinci
    return hewan

def tambahhewan():
    anjing = 20 
    tambahan = anjing + kelinci
    return tambahan

In [62]:
tambahhewan() # karena kelinci tidak define karena kelinci ada di variable yang berbeda

NameError: name 'kelinci' is not defined

In [63]:
kucing = 20 

def jumlahhewan():
    kelinci = 30 
    hewan = kucing + kelinci
    return hewan

def tambahhewan():
    anjing = 20 
    tambahan = anjing + kucing
    return tambahan

In [64]:
tambahhewan()

40

In [65]:
import sys

In [66]:
sys.path

['C:\\Users\\ASUS',
 'C:\\Users\\ASUS\\anaconda3\\python37.zip',
 'C:\\Users\\ASUS\\anaconda3\\DLLs',
 'C:\\Users\\ASUS\\anaconda3\\lib',
 'C:\\Users\\ASUS\\anaconda3',
 '',
 'C:\\Users\\ASUS\\anaconda3\\lib\\site-packages',
 'C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\ASUS\\.ipython']

In [67]:
sys.path.append(r'\Users\ASUS\Desktop\H8package')

In [68]:
sys.path

['C:\\Users\\ASUS',
 'C:\\Users\\ASUS\\anaconda3\\python37.zip',
 'C:\\Users\\ASUS\\anaconda3\\DLLs',
 'C:\\Users\\ASUS\\anaconda3\\lib',
 'C:\\Users\\ASUS\\anaconda3',
 '',
 'C:\\Users\\ASUS\\anaconda3\\lib\\site-packages',
 'C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\ASUS\\.ipython',
 '\\Users\\ASUS\\Desktop\\H8package']

In [69]:
import mod

Hacktiv8 Inalum for Data Science


In [70]:
mod.s

'Hacktiv8 Inalum for Data Science'

In [71]:
mod.a

[100, 200, 300]

In [72]:
mod.foo()

TypeError: foo() missing 1 required positional argument: 'arg'

In [73]:
mod.foo('kukuh')

kukuh


In [74]:
from mod import s, foo

In [75]:
s

'Hacktiv8 Inalum for Data Science'

In [76]:
foo('kukuh')

kukuh


In [78]:
from mod import *

In [79]:
s

'Hacktiv8 Inalum for Data Science'

In [80]:
from mod import s as string

In [81]:
string

'Hacktiv8 Inalum for Data Science'

In [82]:
import mod as my_module

In [83]:
my_module.s

'Hacktiv8 Inalum for Data Science'

In [ ]:
import mod1,mod2, mod3 # jika punya banyak module

In [84]:
import H8package.mod

H8package.mod.s

ModuleNotFoundError: No module named 'H8package'

In [85]:
from H8package.mod import s

ModuleNotFoundError: No module named 'H8package'

In [87]:
sys.path.append(r'/Users/ASUS/Desktop/')

In [88]:
import H8package.mod import s

SyntaxError: invalid syntax (<ipython-input-88-7b764234221a>, line 1)

In [89]:
import H8package.mod

H8package.mod.s

Hacktiv8 Inalum for Data Science


'Hacktiv8 Inalum for Data Science'

In [91]:
from H8package.mod import s

In [92]:
s

'Hacktiv8 Inalum for Data Science'

In [93]:
!pip --version

pip 20.0.2 from C:\Users\ASUS\anaconda3\lib\site-packages\pip (python 3.7)



In [95]:
!pip install requests

In [96]:
import requests

## Numpy

In [97]:
import numpy as np

In [98]:
## creating Array

a = np.array([1, 2, 3])

In [99]:
a

array([1, 2, 3])

In [100]:
b = [1, 2, 3]

In [101]:
b

[1, 2, 3]

In [102]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [103]:
c = np.zeros(5)

In [104]:
print(c)

[0. 0. 0. 0. 0.]


In [105]:
d = np.ones(5)

In [106]:
print(d)

[1. 1. 1. 1. 1.]


In [108]:
np.arange(4)

array([0, 1, 2, 3])

In [109]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
np.arange(0,20,2) #start, stop, step

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [111]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [112]:
print(arr)

[1 2 3 4 5 6 7 8]


In [113]:
np.append(arr, [1, 2]) # add

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [114]:
np.delete(arr, 1) # delete

array([1, 3, 4, 5, 6, 7, 8])

In [115]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [116]:
print(arr)

[2 1 5 3 7 4 6 8]


In [117]:
np.sort(arr) # sorting

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
## Shape dan Size

In [120]:
array_example = np.array([[0, 1, 2, 3],
                        [4, 5, 6, 7]])

In [121]:
print(array_example)

[[0 1 2 3]
 [4 5 6 7]]


In [122]:
array_example.ndim

2

In [123]:
array_example.size

8

In [124]:
array_example.shape

(2, 4)

In [130]:
array_example.size

8

In [131]:
array_example.shape

(2, 4)

In [ ]:
# reshape

In [132]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [133]:
b = a.reshape(3, 2)

In [134]:
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [135]:
a.reshape(4, 2) #error karena valuenya ga cukup

ValueError: cannot reshape array of size 6 into shape (4,2)

In [136]:
a. reshape(6, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
# convert 1D to 2D

In [137]:
a

array([0, 1, 2, 3, 4, 5])

In [138]:
a.shape

(6,)

In [140]:
a2 = a[np.newaxis]
print(a2)
print(a2.shape)

[[0 1 2 3 4 5]]
(1, 6)


In [141]:
row_vector = a[np.newaxis, :]
print(row_vector)
print(row_vector.shape)

[[0 1 2 3 4 5]]
(1, 6)


In [142]:
col_vector = a[:, np.newaxis]
print(col_vector)
print(col_vector.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [143]:
print(a)

[0 1 2 3 4 5]


In [144]:
print(a.shape)

(6,)


In [148]:
d = np.expand_dims(a, axis=1)
print(d)
print(d.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [149]:
e = np.expand_dims(a, axis=0)
print(e)
print(e.shape)

[[0 1 2 3 4 5]]
(1, 6)


In [ ]:
## indexing and slicing

In [153]:
data = np.array([1, 2, 3])

In [154]:
data[0]

1

In [155]:
data[0:2]

array([1, 2])

In [156]:
data[1:]

array([2, 3])

In [157]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [158]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [160]:
a[a<5]

array([1, 2, 3, 4])

In [162]:
a[a>=5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [165]:
lebih_lima = (a>= 5)

a[lebih_lima]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [167]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Create array from existing data

In [168]:
arr = np.array([1, 2, 3, 4,  5,  6,  7,  8,  9, 10])

In [169]:
arr1= arr[3: 8]

In [170]:
print(arr1)

[4 5 6 7 8]


In [177]:
a_1 = np.array(([1, 1],
              [2, 2]))

print(a_1)

[[1 1]
 [2 2]]


In [181]:
a_2 = np.array(([3, 3],
              [2, 2]))

print(a_2)

[[3 3]
 [2 2]]


In [185]:
np.vstack((a_1, a_2))

array([[3, 3],
       [2, 2],
       [3, 3],
       [2, 2]])

In [186]:
np.hstack((a_1, a_2))

array([[3, 3, 3, 3],
       [2, 2, 2, 2]])

In [187]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [188]:
np.hsplit(arr, 5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

In [189]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [190]:
b = a.view()

In [191]:
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [192]:
c = a.copy()

In [193]:
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# basic array operations

In [194]:
a_1

array([[3, 3],
       [2, 2]])

In [195]:
a_2

array([[3, 3],
       [2, 2]])

In [196]:
a_2 - a_1

array([[0, 0],
       [0, 0]])

In [197]:
a_2 + a_1

array([[6, 6],
       [4, 4]])

In [198]:
a_2 * a_1

array([[9, 9],
       [4, 4]])

In [199]:
a_2 / a_1

array([[1., 1.],
       [1., 1.]])

In [200]:
arr = np.array([1, 2, 3, 4,  5,  6,  7,  8,  9, 10])

In [201]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [202]:
arr.sum()

55

In [203]:
a_1

array([[3, 3],
       [2, 2]])

In [204]:
a_1.sum()

10

In [205]:
a_1.sum(axis=0)

array([5, 5])

In [206]:
a_1.sum(axis=1)

array([6, 4])

In [207]:
a_1 + 1.6 #broadcasting

array([[4.6, 4.6],
       [3.6, 3.6]])

In [208]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [210]:
a.sum()

78

In [211]:
a.min()

1

In [213]:
a.max()

12

In [214]:
a.min(axis=0)

array([1, 2, 3, 4])

In [215]:
a.min(axis=1)

array([1, 5, 9])

In [216]:
a.max(axis=0)

array([ 9, 10, 11, 12])

In [217]:
np.array([[1, 2], [3,4]])

array([[1, 2],
       [3, 4]])

In [218]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [219]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [220]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [221]:
np.random.random((3, 2))

array([[0.44197446, 0.96297623],
       [0.80086665, 0.51833575],
       [0.42425227, 0.75887606]])

In [ ]:
# Matrix Arithmetic

In [222]:
data = np.array([[1, 2], [3,4]])
print(data)

[[1 2]
 [3 4]]


In [224]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [225]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [226]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [227]:
data + ones_row

array([[2., 3.],
       [4., 5.]])

In [230]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [232]:
np.dot(a_1, a_2) #matrix dikalikan

array([[ 58,  64],
       [139, 154]])

In [233]:
print(a_1.shape)
print(a_2.shape)

(2, 3)
(3, 2)


In [234]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [235]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [237]:
data[0, 1]

2

In [239]:
data[1, 1]

4

In [240]:
data[2, 1]

6

In [241]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [242]:
data[0:2]

array([[1, 2],
       [3, 4]])

In [243]:
data[0:2,0]

array([1, 3])

In [244]:
data[0:2,1]

array([2, 4])

In [245]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [246]:
data.max()

6

In [247]:
data.min()

1

In [248]:
data.sum()

21

In [249]:
data.max(axis=1)

array([2, 4, 6])

In [250]:
data.max(axis=0)

array([5, 6])

In [251]:
# transposing and reshaping

In [252]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [254]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [256]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [258]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [259]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [262]:
arr = np.arange(6).reshape((2, 3))

In [263]:
print(arr)

[[0 1 2]
 [3 4 5]]


In [264]:
# ND Array 

In [271]:
ndarr = np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]]])

In [277]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [278]:
np.zeros((4, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [279]:
np.random.random((4, 3, 2))

array([[[0.52717321, 0.82882548],
        [0.74366787, 0.47408327],
        [0.1183373 , 0.73364626]],

       [[0.46640559, 0.23937312],
        [0.26218727, 0.64736225],
        [0.2167935 , 0.6179403 ]],

       [[0.23487808, 0.85355041],
        [0.25921993, 0.17430776],
        [0.98218699, 0.89419913]],

       [[0.55321693, 0.35316942],
        [0.91095277, 0.54424902],
        [0.16714941, 0.65141307]]])

In [281]:
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [282]:
# flatten

In [283]:
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [284]:
ndarr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [285]:
a = np.random.random(5)

In [286]:
print(a)

[0.95643538 0.21193609 0.65966229 0.05795435 0.7851621 ]


In [287]:
a.shape # rank 1 Array

(5,)

In [289]:
a.T #tidak bisa ditranspose

array([0.95643538, 0.21193609, 0.65966229, 0.05795435, 0.7851621 ])

In [290]:
np.dot(a, a.T)

2.014678110525187

In [292]:
a = np.random.rand(5, 1) # bikin column vector

In [293]:
print(a)

[[0.78304809]
 [0.11614779]
 [0.73167795]
 [0.70433404]
 [0.17915028]]


In [294]:
a.shape

(5, 1)

In [295]:
a.T #tidak bisa ditranspose

array([[0.78304809, 0.11614779, 0.73167795, 0.70433404, 0.17915028]])

In [296]:
np.dot(a, a.T)

array([[0.6131643 , 0.09094931, 0.57293902, 0.55152742, 0.14028329],
       [0.09094931, 0.01349031, 0.08498278, 0.08180684, 0.02080791],
       [0.57293902, 0.08498278, 0.53535263, 0.51534569, 0.13108031],
       [0.55152742, 0.08180684, 0.51534569, 0.49608644, 0.12618164],
       [0.14028329, 0.02080791, 0.13108031, 0.12618164, 0.03209482]])

In [299]:
a = np.random.rand(1, 5)

In [300]:
a.shape

(1, 5)

In [301]:
a

array([[0.0079124 , 0.05684924, 0.28470969, 0.79642465, 0.3529532 ]])

In [303]:
ndarr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [304]:
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])